/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'actionType' : string,
  'paymentDetails' : [] | [string],
  'timestamp' : Time,
  'comments' : [] | [string],
  'outcome' : string,
}
export interface Case {
  'id' : CaseID,
  'dpd' : bigint,
  'status' : CaseStatus,
  'debtorName' : string,
  'payoffBalance' : number,
  'customerId' : string,
  'amountDue' : number,
  'phoneNumber' : string,
  'paidAmount' : number,
  'contractId' : string,
}
export type CaseID = string;
export type CaseStatus = { 'ptp' : null } |
  { 'active' : null } |
  { 'escalated' : null };
export interface Comment {
  'action' : string,
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
  'outcome' : string,
}
export interface Document {
  'id' : DocumentID,
  'name' : string,
  'fileType' : string,
  'blobReference' : ExternalBlob,
}
export type DocumentID = string;
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivity' : ActorMethod<[CaseID, Activity], undefined>,
  'addComment' : ActorMethod<[CaseID, string, string, string], undefined>,
  'addDocument' : ActorMethod<[CaseID, Document], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<[Case], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[CaseID], [] | [Case]>,
  'getCaseActivities' : ActorMethod<[CaseID], Array<Activity>>,
  'getCaseComments' : ActorMethod<[CaseID], Array<Comment>>,
  'getCaseDocuments' : ActorMethod<[CaseID], Array<Document>>,
  'getCases' : ActorMethod<[], Array<Case>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];