/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CaseID = IDL.Text;
export const Time = IDL.Int;
export const Activity = IDL.Record({
  'ptpDate' : IDL.Opt(IDL.Text),
  'actionType' : IDL.Text,
  'ptpAmount' : IDL.Opt(IDL.Float64),
  'paymentDetails' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'comments' : IDL.Opt(IDL.Text),
  'outcome' : IDL.Text,
});
export const DocumentID = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : DocumentID,
  'name' : IDL.Text,
  'fileType' : IDL.Text,
  'blobReference' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CaseStatus = IDL.Variant({
  'ptp' : IDL.Null,
  'active' : IDL.Null,
  'escalated' : IDL.Null,
});
export const Case = IDL.Record({
  'id' : CaseID,
  'dpd' : IDL.Nat,
  'status' : CaseStatus,
  'secondaryContact' : IDL.Text,
  'debtorName' : IDL.Text,
  'productType' : IDL.Text,
  'payoffBalance' : IDL.Float64,
  'customerId' : IDL.Text,
  'amountDue' : IDL.Float64,
  'phoneNumber' : IDL.Text,
  'paidAmount' : IDL.Float64,
  'primaryContact' : IDL.Text,
  'contractId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivity' : IDL.Func([CaseID, Activity], [], []),
  'addDocument' : IDL.Func([CaseID, Document], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func([Case], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([CaseID], [IDL.Opt(Case)], ['query']),
  'getCaseActivities' : IDL.Func([CaseID], [IDL.Vec(Activity)], ['query']),
  'getCaseDocuments' : IDL.Func([CaseID], [IDL.Vec(Document)], ['query']),
  'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CaseID = IDL.Text;
  const Time = IDL.Int;
  const Activity = IDL.Record({
    'ptpDate' : IDL.Opt(IDL.Text),
    'actionType' : IDL.Text,
    'ptpAmount' : IDL.Opt(IDL.Float64),
    'paymentDetails' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'comments' : IDL.Opt(IDL.Text),
    'outcome' : IDL.Text,
  });
  const DocumentID = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : DocumentID,
    'name' : IDL.Text,
    'fileType' : IDL.Text,
    'blobReference' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CaseStatus = IDL.Variant({
    'ptp' : IDL.Null,
    'active' : IDL.Null,
    'escalated' : IDL.Null,
  });
  const Case = IDL.Record({
    'id' : CaseID,
    'dpd' : IDL.Nat,
    'status' : CaseStatus,
    'secondaryContact' : IDL.Text,
    'debtorName' : IDL.Text,
    'productType' : IDL.Text,
    'payoffBalance' : IDL.Float64,
    'customerId' : IDL.Text,
    'amountDue' : IDL.Float64,
    'phoneNumber' : IDL.Text,
    'paidAmount' : IDL.Float64,
    'primaryContact' : IDL.Text,
    'contractId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivity' : IDL.Func([CaseID, Activity], [], []),
    'addDocument' : IDL.Func([CaseID, Document], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func([Case], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([CaseID], [IDL.Opt(Case)], ['query']),
    'getCaseActivities' : IDL.Func([CaseID], [IDL.Vec(Activity)], ['query']),
    'getCaseDocuments' : IDL.Func([CaseID], [IDL.Vec(Document)], ['query']),
    'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };